spring:
  application:
    name: career-ai
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.tanisha.career_ai: DEBUG

groq:
  api:
    key: ${GROQ_API_KEY:}
    model: ${GROQ_MODEL:openai/gpt-oss-120b}

rapid:
  api:
    key: ${RAPID_API_KEY:}
supabase:
  url: https://aktgmluowkkzdedyuiev.supabase.co
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:}
oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID:}
    client-secret: ${GOOGLE_CLIENT_SECRET:}
    redirect-uri: http://localhost:8080/auth/google/callback
  linkedin:
    client-id: ${LINKEDIN_CLIENT_ID:}
    client-secret: ${LINKEDIN_CLIENT_SECRET:}
    redirect-uri: http://localhost:8080/auth/linkedin/callback
